# 数据增强
use_specaug: True
use_textaug: False

# text enhancement
# enhancement_type: the type of enhancement(1/2/3/4)
#                          type 1: Enhancement based on consonant and vowel
#                          type 2: Enhancement based on data distribution
#                          type 3: Enhancement based on literally random
#                          type 4: Enhancement based on setting zero
char_embed_size: 512
mutation_prob: 0.1
enhancement_type: 1
phone_num: 43

## 统计
#pretrained_model: 'checkpoint/ctc_fbank_cnn_vc10/ctc_best_model.pkl'
exp_name: 'ctc_contrast_pretrained_ctc_fbank_cnn_vc10'
checkpoint_dir: 'checkpoint/'

#Data
vocab_file: 'data/units'
train_wavscp_path: 'data/train/wav.scp'
train_scp_path: 'data/train/fbank.scp'
train_lab_path: 'data/train/phn_text'
train_trans_path: 'data/train/transcript_phn_text'
valid_wavscp_path: 'data/dev/wav.scp'
valid_scp_path: 'data/dev/fbank.scp'
valid_lab_path: 'data/dev/phn_text'
valid_trans_path: 'data/dev/transcript_phn_text'
left_ctx: 0
right_ctx: 2
n_skip_frame: 2
n_downsample: 2
num_workers: 1
shuffle_train: True
feature_dim: 81
# 39 + 1 (sil) + 1 (err) + 1 (unk)
output_class_dim: 43
mel: False
feature_type: "fbank"

#Model
rnn_input_size: 243
rnn_hidden_size: 384
rnn_layers: 4
rnn_type: "nn.LSTM"
bidirectional: True
batch_norm: True
drop_out: 0.2

#CNN
add_cnn: True
layers: 2
channel: "[(1, 32), (32, 32)]"
kernel_size: "[(3, 3), (3, 3)]"
stride: "[(1, 2), (2, 2)]"
padding: "[(1, 1), (1, 1)]"
pooling: "None"
batch_norm: True
activation_function: "relu"

#[Training]
use_gpu: True
init_lr: 0.001
num_epoches: 500
end_adjust_acc: 2
lr_decay: 0.5
# 8
batch_size: 64
weight_decay: 0.0005
seed: 1234
verbose_step: 50
# Loss
loss: CTCContrast

#[test]
test_wavscp_path: 'data/test/wav.scp'
test_scp_path: 'data/test/fbank.scp'
test_lab_path: 'data/test/phn_text'
test_trans_path: 'data/test/transcript_phn_text'
decode_type: "Nono"
beam_width: 10
lm_alpha: 0
lm_path: 'data/lm_phone_bg.arpa'

